language: node_js
node_js:
- lts/gallium
install:
- npm install
script:
- npm run build:all
after_script:
- cd dist
- echo 'notes.thyiad.top' > CNAME
- git init
- git add -A
- git commit -m 'deploy'
- git push -f "https://${GITHUB_TOKEN}@${GH_REF}" gh
branches:
  only:
  - main
env:
  global:
    - GH_REF: github.com/Thyiad/notes.git
    - secure: "hT0ppQGNemJfk7nz3WTOSYSEhgBSEjuF0FYqCus6ImqoPkQgPKqabC8c3uCZrg/z+B2Mw4qWcNTYRu9DNF0NuaSji89V8JlT/uNxTFosnKhwh8WtX1wsRA0dJVdN/0GMB0gT11DASsopiC51/bjnXUcU8gvxf1ChcH+qTadzulTdgzhoQEpswgVfkwJiBygICSHQN0dQa9WBXJPe5Gn0xmwluQD73JQ+LP0UY3MSjLrYBE3eeOaxkMjhgp56YGjB57uFbJZVoshYjUdr2YuyLD5pXyM6mVBXXrKl/RVVpzxTviSPbycRz3JUvKQwvD3UfI7UVng9zmLYFcLDBJxOKjgcIVFoeGFcTcfU8RzPFSkMeR+FUAsCQwrMUPi5pvoqVFRrnGYhf/eMS4bDOnCEWaBiiiYgsSA4PK1ecphBVR6soIvYjHogBS2yhoMVbXkNdjc1SWBrRuwyZyQUrOB+AewdSUIsXhWaT4aoXZhSUp5m1y0mJpwCL8Sp5S0hSZL4Qb7iC3yIgC9QHahDvMFrxi5y2RstL/mpESQsN7ygZ2QFN5SwDWAhJuEc/PX9kvJdJTEh+nqAE9CKwzML8h4lGrh3WZNZB1tEsaKmJKzky8SvtswPbtkADdWW2JCW3RR2pQ1r+aQ5UkQ5xcENEe5xaVOMpJo6EjSejmQFW4GqELk="
